{"level":"error","timestamp":"2024-03-12 00:22:43.497","caller":"bootstrap/rabbitmq.go:26","msg":"Exception (403) Reason: \"no access to this vhost\""}
{"level":"error","timestamp":"2024-03-12 23:26:12.484","caller":"bootstrap/rabbitmq.go:26","msg":"Exception (403) Reason: \"no access to this vhost\""}
{"level":"error","timestamp":"2024-03-12 23:29:36.660","caller":"bootstrap/rabbitmq.go:26","msg":"Exception (403) Reason: \"no access to this vhost\""}
{"level":"error","timestamp":"2024-03-12 23:30:41.835","caller":"bootstrap/rabbitmq.go:26","msg":"Exception (403) Reason: \"no access to this vhost\""}
{"level":"error","timestamp":"2024-03-12 23:30:55.250","caller":"bootstrap/rabbitmq.go:26","msg":"Exception (403) Reason: \"no access to this vhost\""}
{"level":"error","timestamp":"2024-03-12 23:31:47.495","caller":"bootstrap/rabbitmq.go:26","msg":"Exception (403) Reason: \"no access to this vhost\""}
{"level":"error","timestamp":"2024-03-12 23:32:40.033","caller":"bootstrap/rabbitmq.go:26","msg":"Exception (403) Reason: \"no access to this vhost\""}
{"level":"error","timestamp":"2024-03-12 23:32:53.318","caller":"bootstrap/rabbitmq.go:26","msg":"Exception (403) Reason: \"no access to this vhost\""}
{"level":"error","timestamp":"2024-03-12 23:33:21.120","caller":"bootstrap/rabbitmq.go:26","msg":"Exception (403) Reason: \"no access to this vhost\""}
{"level":"error","timestamp":"2024-03-12 23:38:05.107","caller":"bootstrap/rabbitmq.go:26","msg":"Exception (403) Reason: \"no access to this vhost\""}
{"level":"error","timestamp":"2024-03-12 23:46:31.892","caller":"bootstrap/rabbitmq.go:28","msg":"Exception (403) Reason: \"no access to this vhost\""}
{"level":"error","timestamp":"2024-03-25 19:05:43.602","caller":"global/app.go:64","msg":"日志发送失败: 秒杀活动宕机--------------> - 错误详情: Exception (504) Reason: \"channel/connection is not open\""}
{"level":"error","timestamp":"2024-03-25 19:05:43.639","caller":"global/app.go:65","msg":"Exception (504) Reason: \"channel/connection is not open\""}
{"level":"error","timestamp":"2024-03-25 19:05:43.602","caller":"global/app.go:64","msg":"日志发送失败: 秒杀活动宕机--------------> - 错误详情: Exception (530) Reason: \"NOT_ALLOWED - attempt to reuse consumer tag '4'\""}
{"level":"error","timestamp":"2024-03-25 19:05:43.639","caller":"global/app.go:65","msg":"Exception (504) Reason: \"channel/connection is not open\""}
{"level":"error","timestamp":"2024-03-25 19:05:43.602","caller":"global/app.go:64","msg":"日志发送失败: 秒杀活动宕机--------------> - 错误详情: Exception (504) Reason: \"channel/connection is not open\""}
{"level":"error","timestamp":"2024-03-25 19:05:43.639","caller":"global/app.go:65","msg":"Exception (504) Reason: \"channel/connection is not open\""}
{"level":"error","timestamp":"2024-03-25 19:12:39.797","caller":"global/app.go:64","msg":"日志发送失败: 秒杀活动宕机--------------> - 错误详情: Exception (504) Reason: \"channel/connection is not open\""}
{"level":"error","timestamp":"2024-03-25 19:12:39.798","caller":"global/app.go:64","msg":"日志发送失败: 秒杀活动宕机--------------> - 错误详情: Exception (530) Reason: \"NOT_ALLOWED - attempt to reuse consumer tag '4'\""}
{"level":"error","timestamp":"2024-03-25 19:12:39.798","caller":"global/app.go:64","msg":"日志发送失败: 秒杀活动宕机--------------> - 错误详情: Exception (504) Reason: \"channel/connection is not open\""}
{"level":"error","timestamp":"2024-03-25 19:12:39.874","caller":"global/app.go:65","msg":"Exception (504) Reason: \"channel/connection is not open\""}
{"level":"error","timestamp":"2024-03-25 19:12:39.874","caller":"global/app.go:65","msg":"Exception (504) Reason: \"channel/connection is not open\""}
{"level":"error","timestamp":"2024-03-25 19:12:39.874","caller":"global/app.go:65","msg":"Exception (504) Reason: \"channel/connection is not open\""}
{"level":"error","timestamp":"2024-03-25 19:13:20.919","caller":"global/app.go:64","msg":"日志发送失败: 秒杀活动宕机--------------> - 错误详情: Exception (504) Reason: \"channel/connection is not open\""}
{"level":"error","timestamp":"2024-03-25 19:13:20.920","caller":"global/app.go:65","msg":"Exception (504) Reason: \"channel/connection is not open\""}
{"level":"error","timestamp":"2024-03-25 19:13:20.920","caller":"global/app.go:64","msg":"日志发送失败: 秒杀活动宕机--------------> - 错误详情: Exception (530) Reason: \"NOT_ALLOWED - attempt to reuse consumer tag '4'\""}
{"level":"error","timestamp":"2024-03-25 19:13:20.920","caller":"global/app.go:65","msg":"Exception (504) Reason: \"channel/connection is not open\""}
{"level":"error","timestamp":"2024-03-25 19:13:20.920","caller":"global/app.go:64","msg":"日志发送失败: 秒杀活动宕机--------------> - 错误详情: Exception (504) Reason: \"channel/connection is not open\""}
{"level":"error","timestamp":"2024-03-25 19:13:20.920","caller":"global/app.go:65","msg":"Exception (504) Reason: \"channel/connection is not open\""}
{"level":"error","timestamp":"2024-03-25 19:16:20.736","caller":"global/app.go:64","msg":"日志发送失败: 秒杀活动宕机--------------> - 错误详情: Exception (530) Reason: \"NOT_ALLOWED - attempt to reuse consumer tag '4'\""}
{"level":"error","timestamp":"2024-03-25 19:16:20.736","caller":"global/app.go:64","msg":"日志发送失败: 秒杀活动宕机--------------> - 错误详情: Exception (504) Reason: \"channel/connection is not open\""}
{"level":"error","timestamp":"2024-03-25 19:16:20.736","caller":"global/app.go:65","msg":"Exception (504) Reason: \"channel/connection is not open\""}
{"level":"error","timestamp":"2024-03-25 19:16:20.736","caller":"global/app.go:65","msg":"Exception (504) Reason: \"channel/connection is not open\""}
{"level":"error","timestamp":"2024-03-25 19:16:20.736","caller":"global/app.go:64","msg":"日志发送失败: 秒杀活动宕机--------------> - 错误详情: Exception (504) Reason: \"channel/connection is not open\""}
{"level":"error","timestamp":"2024-03-25 19:16:20.736","caller":"global/app.go:65","msg":"Exception (504) Reason: \"channel/connection is not open\""}
{"level":"error","timestamp":"2024-03-25 19:21:41.402","caller":"global/app.go:64","msg":"日志发送失败: 秒杀活动宕机--------------> - 错误详情: Exception (504) Reason: \"channel/connection is not open\"\n"}
{"level":"error","timestamp":"2024-03-25 19:21:41.480","caller":"global/app.go:65","msg":"Exception (504) Reason: \"channel/connection is not open\""}
{"level":"error","timestamp":"2024-03-25 19:21:41.402","caller":"global/app.go:64","msg":"日志发送失败: 秒杀活动宕机--------------> - 错误详情: Exception (530) Reason: \"NOT_ALLOWED - attempt to reuse consumer tag '4'\"\n"}
{"level":"error","timestamp":"2024-03-25 19:21:41.480","caller":"global/app.go:65","msg":"Exception (504) Reason: \"channel/connection is not open\""}
{"level":"error","timestamp":"2024-03-25 19:21:41.402","caller":"global/app.go:64","msg":"日志发送失败: 秒杀活动宕机--------------> - 错误详情: Exception (504) Reason: \"channel/connection is not open\"\n"}
{"level":"error","timestamp":"2024-03-25 19:21:41.480","caller":"global/app.go:65","msg":"Exception (504) Reason: \"channel/connection is not open\""}
{"level":"error","timestamp":"2024-03-25 19:21:45.984","caller":"global/app.go:64","msg":"日志发送失败: 秒杀请求-请求入队错误 - 错误详情: Exception (504) Reason: \"channel/connection is not open\"\n"}
{"level":"error","timestamp":"2024-03-25 19:21:45.984","caller":"global/app.go:65","msg":"Exception (504) Reason: \"channel/connection is not open\""}
{"level":"error","timestamp":"2024-03-25 19:21:47.899","caller":"global/app.go:64","msg":"日志发送失败: 秒杀请求-请求入队错误 - 错误详情: Exception (504) Reason: \"channel/connection is not open\"\n"}
{"level":"error","timestamp":"2024-03-25 19:21:47.899","caller":"global/app.go:65","msg":"Exception (504) Reason: \"channel/connection is not open\""}
{"level":"error","timestamp":"2024-03-25 19:21:49.799","caller":"global/app.go:64","msg":"日志发送失败: 秒杀请求-请求入队错误 - 错误详情: Exception (504) Reason: \"channel/connection is not open\"\n"}
{"level":"error","timestamp":"2024-03-25 19:21:49.799","caller":"global/app.go:65","msg":"Exception (504) Reason: \"channel/connection is not open\""}
{"level":"error","timestamp":"2024-03-25 19:21:52.527","caller":"global/app.go:64","msg":"日志发送失败: 秒杀请求-请求入队错误 - 错误详情: Exception (504) Reason: \"channel/connection is not open\"\n"}
{"level":"error","timestamp":"2024-03-25 19:21:52.527","caller":"global/app.go:65","msg":"Exception (504) Reason: \"channel/connection is not open\""}
{"level":"error","timestamp":"2024-03-25 19:21:55.972","caller":"global/app.go:64","msg":"日志发送失败: 秒杀请求-请求入队错误 - 错误详情: Exception (504) Reason: \"channel/connection is not open\"\n"}
{"level":"error","timestamp":"2024-03-25 19:21:55.972","caller":"global/app.go:65","msg":"Exception (504) Reason: \"channel/connection is not open\""}
{"level":"error","timestamp":"2024-03-25 19:22:17.090","caller":"global/app.go:64","msg":"日志发送失败: 秒杀请求-请求入队错误 - 错误详情: Exception (504) Reason: \"channel/connection is not open\"\n"}
{"level":"error","timestamp":"2024-03-25 19:22:17.090","caller":"global/app.go:65","msg":"Exception (504) Reason: \"channel/connection is not open\""}
{"level":"error","timestamp":"2024-03-25 19:22:18.496","caller":"global/app.go:64","msg":"日志发送失败: 秒杀请求-请求入队错误 - 错误详情: Exception (504) Reason: \"channel/connection is not open\"\n"}
{"level":"error","timestamp":"2024-03-25 19:22:18.496","caller":"global/app.go:65","msg":"Exception (504) Reason: \"channel/connection is not open\""}
{"level":"error","timestamp":"2024-03-25 19:22:19.273","caller":"global/app.go:64","msg":"日志发送失败: 秒杀请求-请求入队错误 - 错误详情: Exception (504) Reason: \"channel/connection is not open\"\n"}
{"level":"error","timestamp":"2024-03-25 19:22:19.273","caller":"global/app.go:65","msg":"Exception (504) Reason: \"channel/connection is not open\""}
{"level":"error","timestamp":"2024-03-25 19:22:35.138","caller":"global/app.go:64","msg":"日志发送失败: 秒杀请求-请求入队错误 - 错误详情: Exception (504) Reason: \"channel/connection is not open\"\n"}
{"level":"error","timestamp":"2024-03-25 19:22:35.138","caller":"global/app.go:65","msg":"Exception (504) Reason: \"channel/connection is not open\""}
{"level":"error","timestamp":"2024-03-25 19:22:37.622","caller":"global/app.go:64","msg":"日志发送失败: 秒杀请求-请求入队错误 - 错误详情: Exception (504) Reason: \"channel/connection is not open\"\n"}
{"level":"error","timestamp":"2024-03-25 19:22:37.622","caller":"global/app.go:65","msg":"Exception (504) Reason: \"channel/connection is not open\""}
{"level":"error","timestamp":"2024-03-25 19:23:53.387","caller":"global/app.go:64","msg":"日志发送失败: 秒杀活动宕机--------------> - 错误详情: Exception (504) Reason: \"channel/connection is not open\"\n"}
{"level":"error","timestamp":"2024-03-25 19:23:53.387","caller":"global/app.go:65","msg":"Exception (504) Reason: \"channel/connection is not open\""}
{"level":"error","timestamp":"2024-03-25 19:23:53.387","caller":"global/app.go:64","msg":"日志发送失败: 秒杀活动宕机--------------> - 错误详情: Exception (530) Reason: \"NOT_ALLOWED - attempt to reuse consumer tag '4'\"\n"}
{"level":"error","timestamp":"2024-03-25 19:23:53.388","caller":"global/app.go:65","msg":"Exception (504) Reason: \"channel/connection is not open\""}
{"level":"error","timestamp":"2024-03-25 19:23:53.387","caller":"global/app.go:64","msg":"日志发送失败: 秒杀活动宕机--------------> - 错误详情: Exception (504) Reason: \"channel/connection is not open\"\n"}
{"level":"error","timestamp":"2024-03-25 19:23:53.388","caller":"global/app.go:65","msg":"Exception (504) Reason: \"channel/connection is not open\""}
{"level":"error","timestamp":"2024-03-25 19:23:56.585","caller":"global/app.go:64","msg":"日志发送失败: 测试日志-------------\n"}
{"level":"error","timestamp":"2024-03-25 19:23:56.585","caller":"global/app.go:65","msg":"Exception (504) Reason: \"channel/connection is not open\""}
{"level":"error","timestamp":"2024-03-25 19:23:56.585","caller":"global/app.go:64","msg":"日志发送失败: 秒杀请求-请求入队错误 - 错误详情: Exception (504) Reason: \"channel/connection is not open\"\n"}
{"level":"error","timestamp":"2024-03-25 19:23:56.585","caller":"global/app.go:65","msg":"Exception (504) Reason: \"channel/connection is not open\""}
{"level":"error","timestamp":"2024-03-25 19:23:59.280","caller":"global/app.go:64","msg":"日志发送失败: 测试日志-------------\n"}
{"level":"error","timestamp":"2024-03-25 19:23:59.280","caller":"global/app.go:65","msg":"Exception (504) Reason: \"channel/connection is not open\""}
{"level":"error","timestamp":"2024-03-25 19:23:59.280","caller":"global/app.go:64","msg":"日志发送失败: 秒杀请求-请求入队错误 - 错误详情: Exception (504) Reason: \"channel/connection is not open\"\n"}
{"level":"error","timestamp":"2024-03-25 19:23:59.280","caller":"global/app.go:65","msg":"Exception (504) Reason: \"channel/connection is not open\""}
{"level":"error","timestamp":"2024-03-25 21:50:56.088","caller":"global/app.go:64","msg":"日志发送失败: 秒杀活动宕机--------------> - 错误详情: Exception (530) Reason: \"NOT_ALLOWED - attempt to reuse consumer tag '4'\"\n"}
{"level":"error","timestamp":"2024-03-25 21:50:56.088","caller":"global/app.go:64","msg":"日志发送失败: 秒杀活动宕机--------------> - 错误详情: Exception (504) Reason: \"channel/connection is not open\"\n"}
{"level":"error","timestamp":"2024-03-25 21:50:56.113","caller":"global/app.go:65","msg":"Exception (504) Reason: \"channel/connection is not open\""}
{"level":"error","timestamp":"2024-03-25 21:50:56.088","caller":"global/app.go:64","msg":"日志发送失败: 秒杀活动宕机--------------> - 错误详情: Exception (504) Reason: \"channel/connection is not open\"\n"}
{"level":"error","timestamp":"2024-03-25 21:50:56.113","caller":"global/app.go:65","msg":"Exception (504) Reason: \"channel/connection is not open\""}
{"level":"error","timestamp":"2024-03-25 21:50:56.113","caller":"global/app.go:65","msg":"Exception (504) Reason: \"channel/connection is not open\""}
{"level":"error","timestamp":"2024-03-25 21:56:55.505","caller":"global/app.go:64","msg":"日志发送失败: 测试日志-------------\n"}
{"level":"error","timestamp":"2024-03-25 21:56:55.505","caller":"global/app.go:65","msg":"Exception (504) Reason: \"channel/connection is not open\""}
{"level":"error","timestamp":"2024-03-25 21:56:55.505","caller":"global/app.go:64","msg":"日志发送失败: 秒杀请求-请求入队错误 - 错误详情: Exception (504) Reason: \"channel/connection is not open\"\n"}
{"level":"error","timestamp":"2024-03-25 21:56:55.505","caller":"global/app.go:65","msg":"Exception (504) Reason: \"channel/connection is not open\""}
{"level":"error","timestamp":"2024-03-25 22:28:47.619","caller":"global/app.go:64","msg":"日志发送失败: 测试日志-------------\n"}
{"level":"error","timestamp":"2024-03-25 22:28:47.629","caller":"global/app.go:65","msg":"Exception (504) Reason: \"channel/connection is not open\""}
{"level":"error","timestamp":"2024-03-25 22:28:47.629","caller":"global/app.go:64","msg":"日志发送失败: 秒杀请求-请求入队错误 - 错误详情: Exception (504) Reason: \"channel/connection is not open\"\n"}
{"level":"error","timestamp":"2024-03-25 22:28:47.629","caller":"global/app.go:65","msg":"Exception (504) Reason: \"channel/connection is not open\""}
{"level":"error","timestamp":"2024-03-25 22:29:44.232","caller":"global/app.go:64","msg":"日志发送失败: 测试日志-------------\n"}
{"level":"error","timestamp":"2024-03-25 22:29:44.232","caller":"global/app.go:65","msg":"Exception (504) Reason: \"channel/connection is not open\""}
{"level":"error","timestamp":"2024-03-25 22:29:44.232","caller":"global/app.go:64","msg":"日志发送失败: 秒杀请求-请求入队错误 - 错误详情: Exception (504) Reason: \"channel/connection is not open\"\n"}
{"level":"error","timestamp":"2024-03-25 22:29:44.232","caller":"global/app.go:65","msg":"Exception (504) Reason: \"channel/connection is not open\""}
{"level":"error","timestamp":"2024-03-25 22:29:45.641","caller":"global/app.go:64","msg":"日志发送失败: 测试日志-------------\n"}
{"level":"error","timestamp":"2024-03-25 22:29:45.641","caller":"global/app.go:65","msg":"Exception (504) Reason: \"channel/connection is not open\""}
{"level":"error","timestamp":"2024-03-25 22:29:45.641","caller":"global/app.go:64","msg":"日志发送失败: 秒杀请求-请求入队错误 - 错误详情: Exception (504) Reason: \"channel/connection is not open\"\n"}
{"level":"error","timestamp":"2024-03-25 22:29:45.641","caller":"global/app.go:65","msg":"Exception (504) Reason: \"channel/connection is not open\""}
{"level":"error","timestamp":"2024-03-25 22:29:46.464","caller":"global/app.go:64","msg":"日志发送失败: 测试日志-------------\n"}
{"level":"error","timestamp":"2024-03-25 22:29:46.464","caller":"global/app.go:65","msg":"Exception (504) Reason: \"channel/connection is not open\""}
{"level":"error","timestamp":"2024-03-25 22:29:46.464","caller":"global/app.go:64","msg":"日志发送失败: 秒杀请求-请求入队错误 - 错误详情: Exception (504) Reason: \"channel/connection is not open\"\n"}
{"level":"error","timestamp":"2024-03-25 22:29:46.464","caller":"global/app.go:65","msg":"Exception (504) Reason: \"channel/connection is not open\""}
{"level":"error","timestamp":"2024-03-25 22:29:47.410","caller":"global/app.go:64","msg":"日志发送失败: 测试日志-------------\n"}
{"level":"error","timestamp":"2024-03-25 22:29:47.410","caller":"global/app.go:65","msg":"Exception (504) Reason: \"channel/connection is not open\""}
{"level":"error","timestamp":"2024-03-25 22:29:47.410","caller":"global/app.go:64","msg":"日志发送失败: 秒杀请求-请求入队错误 - 错误详情: Exception (504) Reason: \"channel/connection is not open\"\n"}
{"level":"error","timestamp":"2024-03-25 22:29:47.410","caller":"global/app.go:65","msg":"Exception (504) Reason: \"channel/connection is not open\""}
{"level":"error","timestamp":"2024-03-25 22:29:48.714","caller":"global/app.go:64","msg":"日志发送失败: 测试日志-------------\n"}
{"level":"error","timestamp":"2024-03-25 22:29:48.714","caller":"global/app.go:65","msg":"Exception (504) Reason: \"channel/connection is not open\""}
{"level":"error","timestamp":"2024-03-25 22:29:48.714","caller":"global/app.go:64","msg":"日志发送失败: 秒杀请求-请求入队错误 - 错误详情: Exception (504) Reason: \"channel/connection is not open\"\n"}
{"level":"error","timestamp":"2024-03-25 22:29:48.714","caller":"global/app.go:65","msg":"Exception (504) Reason: \"channel/connection is not open\""}
{"level":"error","timestamp":"2024-03-25 22:29:49.255","caller":"global/app.go:64","msg":"日志发送失败: 测试日志-------------\n"}
{"level":"error","timestamp":"2024-03-25 22:29:49.256","caller":"global/app.go:65","msg":"Exception (504) Reason: \"channel/connection is not open\""}
{"level":"error","timestamp":"2024-03-25 22:29:49.256","caller":"global/app.go:64","msg":"日志发送失败: 秒杀请求-请求入队错误 - 错误详情: Exception (504) Reason: \"channel/connection is not open\"\n"}
{"level":"error","timestamp":"2024-03-25 22:29:49.256","caller":"global/app.go:65","msg":"Exception (504) Reason: \"channel/connection is not open\""}
{"level":"error","timestamp":"2024-03-25 22:34:33.088","caller":"global/app.go:64","msg":"日志发送失败: 秒杀请求-请求入队错误 - 错误详情: Exception (504) Reason: \"channel/connection is not open\"\n"}
{"level":"error","timestamp":"2024-03-25 22:34:33.094","caller":"global/app.go:65","msg":"Exception (504) Reason: \"channel/connection is not open\""}
{"level":"error","timestamp":"2024-03-25 22:45:48.534","caller":"global/app.go:64","msg":"日志发送失败: 秒杀请求-请求入队错误 - 错误详情: Exception (504) Reason: \"channel/connection is not open\"\n"}
{"level":"error","timestamp":"2024-03-25 22:45:48.592","caller":"global/app.go:65","msg":"Exception (504) Reason: \"channel/connection is not open\""}
{"level":"error","timestamp":"2024-03-25 22:45:50.145","caller":"global/app.go:64","msg":"日志发送失败: 秒杀请求-请求入队错误 - 错误详情: Exception (504) Reason: \"channel/connection is not open\"\n"}
{"level":"error","timestamp":"2024-03-25 22:45:50.145","caller":"global/app.go:65","msg":"Exception (504) Reason: \"channel/connection is not open\""}
{"level":"error","timestamp":"2024-03-25 23:24:22.319","caller":"global/app.go:64","msg":"日志发送失败: 秒杀请求-请求入队错误 - 错误详情: Exception (504) Reason: \"channel/connection is not open\"\n"}
{"level":"error","timestamp":"2024-03-25 23:24:22.327","caller":"global/app.go:65","msg":"Exception (504) Reason: \"channel/connection is not open\""}
{"level":"error","timestamp":"2024-03-25 23:24:23.420","caller":"global/app.go:64","msg":"日志发送失败: 秒杀请求-请求入队错误 - 错误详情: Exception (504) Reason: \"channel/connection is not open\"\n"}
{"level":"error","timestamp":"2024-03-25 23:24:23.420","caller":"global/app.go:65","msg":"Exception (504) Reason: \"channel/connection is not open\""}
{"level":"error","timestamp":"2024-03-25 23:24:24.800","caller":"global/app.go:64","msg":"日志发送失败: 秒杀请求-请求入队错误 - 错误详情: Exception (504) Reason: \"channel/connection is not open\"\n"}
{"level":"error","timestamp":"2024-03-25 23:24:24.800","caller":"global/app.go:65","msg":"Exception (504) Reason: \"channel/connection is not open\""}
{"level":"error","timestamp":"2024-03-25 23:25:14.720","caller":"global/app.go:64","msg":"日志发送失败: 秒杀请求-请求入队错误 - 错误详情: Exception (504) Reason: \"channel/connection is not open\"\n"}
{"level":"error","timestamp":"2024-03-25 23:25:14.759","caller":"global/app.go:65","msg":"Exception (504) Reason: \"channel/connection is not open\""}
{"level":"error","timestamp":"2024-03-25 23:25:16.728","caller":"global/app.go:64","msg":"日志发送失败: 秒杀请求-请求入队错误 - 错误详情: Exception (504) Reason: \"channel/connection is not open\"\n"}
{"level":"error","timestamp":"2024-03-25 23:25:16.728","caller":"global/app.go:65","msg":"Exception (504) Reason: \"channel/connection is not open\""}
{"level":"error","timestamp":"2024-03-25 23:39:08.019","caller":"global/app.go:64","msg":"日志发送失败: 秒杀请求-请求入队错误 - 错误详情: Exception (504) Reason: \"channel/connection is not open\"\n"}
{"level":"error","timestamp":"2024-03-25 23:39:08.020","caller":"global/app.go:65","msg":"Exception (504) Reason: \"channel/connection is not open\""}
{"level":"error","timestamp":"2024-03-25 23:39:16.856","caller":"global/app.go:64","msg":"日志发送失败: 秒杀请求-请求入队错误 - 错误详情: Exception (504) Reason: \"channel/connection is not open\"\n"}
{"level":"error","timestamp":"2024-03-25 23:39:16.856","caller":"global/app.go:65","msg":"Exception (504) Reason: \"channel/connection is not open\""}
{"level":"error","timestamp":"2024-03-25 23:40:01.741","caller":"global/app.go:64","msg":"日志发送失败: 秒杀请求-请求入队错误 - 错误详情: Exception (504) Reason: \"channel/connection is not open\"\n"}
{"level":"error","timestamp":"2024-03-25 23:40:01.766","caller":"global/app.go:65","msg":"Exception (504) Reason: \"channel/connection is not open\""}
{"level":"error","timestamp":"2024-03-25 23:40:03.299","caller":"global/app.go:64","msg":"日志发送失败: 秒杀请求-请求入队错误 - 错误详情: Exception (504) Reason: \"channel/connection is not open\"\n"}
{"level":"error","timestamp":"2024-03-25 23:40:03.299","caller":"global/app.go:65","msg":"Exception (504) Reason: \"channel/connection is not open\""}
{"level":"error","timestamp":"2024-03-25 23:40:59.203","caller":"global/app.go:64","msg":"日志发送失败: 秒杀请求-请求入队错误 - 错误详情: Exception (504) Reason: \"channel/connection is not open\"\n"}
{"level":"error","timestamp":"2024-03-25 23:40:59.204","caller":"global/app.go:65","msg":"Exception (504) Reason: \"channel/connection is not open\""}
{"level":"error","timestamp":"2024-03-25 23:41:00.667","caller":"global/app.go:64","msg":"日志发送失败: 秒杀请求-请求入队错误 - 错误详情: Exception (504) Reason: \"channel/connection is not open\"\n"}
{"level":"error","timestamp":"2024-03-25 23:41:00.667","caller":"global/app.go:65","msg":"Exception (504) Reason: \"channel/connection is not open\""}
{"level":"error","timestamp":"2024-03-25 23:41:01.399","caller":"global/app.go:64","msg":"日志发送失败: 秒杀请求-请求入队错误 - 错误详情: Exception (504) Reason: \"channel/connection is not open\"\n"}
{"level":"error","timestamp":"2024-03-25 23:41:01.399","caller":"global/app.go:65","msg":"Exception (504) Reason: \"channel/connection is not open\""}
{"level":"error","timestamp":"2024-03-25 23:41:02.598","caller":"global/app.go:64","msg":"日志发送失败: 秒杀请求-请求入队错误 - 错误详情: Exception (504) Reason: \"channel/connection is not open\"\n"}
{"level":"error","timestamp":"2024-03-25 23:41:02.598","caller":"global/app.go:65","msg":"Exception (504) Reason: \"channel/connection is not open\""}
{"level":"error","timestamp":"2024-03-25 23:41:03.959","caller":"global/app.go:64","msg":"日志发送失败: 秒杀请求-请求入队错误 - 错误详情: Exception (504) Reason: \"channel/connection is not open\"\n"}
{"level":"error","timestamp":"2024-03-25 23:41:03.959","caller":"global/app.go:65","msg":"Exception (504) Reason: \"channel/connection is not open\""}
{"level":"error","timestamp":"2024-03-25 23:41:04.801","caller":"global/app.go:64","msg":"日志发送失败: 秒杀请求-请求入队错误 - 错误详情: Exception (504) Reason: \"channel/connection is not open\"\n"}
{"level":"error","timestamp":"2024-03-25 23:41:04.801","caller":"global/app.go:65","msg":"Exception (504) Reason: \"channel/connection is not open\""}
{"level":"error","timestamp":"2024-03-25 23:46:28.261","caller":"global/app.go:64","msg":"日志发送失败: 秒杀请求-请求入队错误 - 错误详情: Exception (504) Reason: \"channel/connection is not open\"\n"}
{"level":"error","timestamp":"2024-03-25 23:46:28.265","caller":"global/app.go:65","msg":"Exception (504) Reason: \"channel/connection is not open\""}
{"level":"error","timestamp":"2024-03-25 23:46:29.676","caller":"global/app.go:64","msg":"日志发送失败: 秒杀请求-请求入队错误 - 错误详情: Exception (504) Reason: \"channel/connection is not open\"\n"}
{"level":"error","timestamp":"2024-03-25 23:46:29.676","caller":"global/app.go:65","msg":"Exception (504) Reason: \"channel/connection is not open\""}
{"level":"error","timestamp":"2024-03-25 23:46:30.694","caller":"global/app.go:64","msg":"日志发送失败: 秒杀请求-请求入队错误 - 错误详情: Exception (504) Reason: \"channel/connection is not open\"\n"}
{"level":"error","timestamp":"2024-03-25 23:46:30.694","caller":"global/app.go:65","msg":"Exception (504) Reason: \"channel/connection is not open\""}
{"level":"error","timestamp":"2024-03-25 23:47:51.834","caller":"global/app.go:64","msg":"日志发送失败: 秒杀请求-请求入队错误 - 错误详情: Exception (504) Reason: \"channel/connection is not open\"\n"}
{"level":"error","timestamp":"2024-03-25 23:47:51.841","caller":"global/app.go:65","msg":"Exception (504) Reason: \"channel/connection is not open\""}
{"level":"error","timestamp":"2024-03-25 23:47:53.071","caller":"global/app.go:64","msg":"日志发送失败: 秒杀请求-请求入队错误 - 错误详情: Exception (504) Reason: \"channel/connection is not open\"\n"}
{"level":"error","timestamp":"2024-03-25 23:47:53.071","caller":"global/app.go:65","msg":"Exception (504) Reason: \"channel/connection is not open\""}
{"level":"error","timestamp":"2024-03-25 23:47:53.964","caller":"global/app.go:64","msg":"日志发送失败: 秒杀请求-请求入队错误 - 错误详情: Exception (504) Reason: \"channel/connection is not open\"\n"}
{"level":"error","timestamp":"2024-03-25 23:47:53.965","caller":"global/app.go:65","msg":"Exception (504) Reason: \"channel/connection is not open\""}
{"level":"error","timestamp":"2024-03-25 23:48:28.152","caller":"global/app.go:64","msg":"日志发送失败: 秒杀活动宕机--------------> - 错误详情: Exception (504) Reason: \"channel/connection is not open\"\n"}
{"level":"error","timestamp":"2024-03-25 23:48:28.229","caller":"global/app.go:65","msg":"Exception (504) Reason: \"channel/connection is not open\""}
{"level":"error","timestamp":"2024-03-25 23:48:28.152","caller":"global/app.go:64","msg":"日志发送失败: 秒杀活动宕机--------------> - 错误详情: Exception (530) Reason: \"NOT_ALLOWED - attempt to reuse consumer tag '1'\"\n"}
{"level":"error","timestamp":"2024-03-25 23:48:28.229","caller":"global/app.go:65","msg":"Exception (504) Reason: \"channel/connection is not open\""}
{"level":"error","timestamp":"2024-03-25 23:48:28.152","caller":"global/app.go:64","msg":"日志发送失败: 秒杀活动宕机--------------> - 错误详情: Exception (504) Reason: \"channel/connection is not open\"\n"}
{"level":"error","timestamp":"2024-03-25 23:48:28.229","caller":"global/app.go:65","msg":"Exception (504) Reason: \"channel/connection is not open\""}
{"level":"error","timestamp":"2024-03-25 23:48:54.308","caller":"global/app.go:64","msg":"日志发送失败: 秒杀活动宕机--------------> - 错误详情: Exception (504) Reason: \"channel/connection is not open\"\n"}
{"level":"error","timestamp":"2024-03-25 23:48:54.308","caller":"global/app.go:64","msg":"日志发送失败: 秒杀活动宕机--------------> - 错误详情: Exception (530) Reason: \"NOT_ALLOWED - attempt to reuse consumer tag '1'\"\n"}
{"level":"error","timestamp":"2024-03-25 23:48:54.425","caller":"global/app.go:65","msg":"Exception (504) Reason: \"channel/connection is not open\""}
{"level":"error","timestamp":"2024-03-25 23:48:54.425","caller":"global/app.go:65","msg":"Exception (504) Reason: \"channel/connection is not open\""}
{"level":"error","timestamp":"2024-03-26 17:43:37.512","caller":"global/app.go:66","msg":"日志发送失败: 秒杀请求-请求入队错误 - 错误详情: Exception (504) Reason: \"channel/connection is not open\"\n"}
{"level":"error","timestamp":"2024-03-26 17:43:37.513","caller":"global/app.go:67","msg":"Exception (504) Reason: \"channel/connection is not open\""}
{"level":"error","timestamp":"2024-03-26 17:43:39.405","caller":"global/app.go:66","msg":"日志发送失败: 秒杀请求-请求入队错误 - 错误详情: Exception (504) Reason: \"channel/connection is not open\"\n"}
{"level":"error","timestamp":"2024-03-26 17:43:39.405","caller":"global/app.go:67","msg":"Exception (504) Reason: \"channel/connection is not open\""}
{"level":"error","timestamp":"2024-03-26 17:43:40.476","caller":"global/app.go:66","msg":"日志发送失败: 秒杀请求-请求入队错误 - 错误详情: Exception (504) Reason: \"channel/connection is not open\"\n"}
{"level":"error","timestamp":"2024-03-26 17:43:40.476","caller":"global/app.go:67","msg":"Exception (504) Reason: \"channel/connection is not open\""}
{"level":"error","timestamp":"2024-03-26 17:43:41.403","caller":"global/app.go:66","msg":"日志发送失败: 秒杀请求-请求入队错误 - 错误详情: Exception (504) Reason: \"channel/connection is not open\"\n"}
{"level":"error","timestamp":"2024-03-26 17:43:41.403","caller":"global/app.go:67","msg":"Exception (504) Reason: \"channel/connection is not open\""}
{"level":"error","timestamp":"2024-03-26 17:43:42.150","caller":"global/app.go:66","msg":"日志发送失败: 秒杀请求-请求入队错误 - 错误详情: Exception (504) Reason: \"channel/connection is not open\"\n"}
{"level":"error","timestamp":"2024-03-26 17:43:42.150","caller":"global/app.go:67","msg":"Exception (504) Reason: \"channel/connection is not open\""}
{"level":"error","timestamp":"2024-03-26 17:43:42.935","caller":"global/app.go:66","msg":"日志发送失败: 秒杀请求-请求入队错误 - 错误详情: Exception (504) Reason: \"channel/connection is not open\"\n"}
{"level":"error","timestamp":"2024-03-26 17:43:42.935","caller":"global/app.go:67","msg":"Exception (504) Reason: \"channel/connection is not open\""}
{"level":"error","timestamp":"2024-03-26 17:48:19.033","caller":"global/app.go:66","msg":"日志发送失败: 订单处理结果消息发布失败 - 错误详情: Exception (504) Reason: \"channel/connection is not open\"\n"}
{"level":"error","timestamp":"2024-03-26 17:48:19.045","caller":"global/app.go:67","msg":"Exception (504) Reason: \"channel/connection is not open\""}
{"level":"error","timestamp":"2024-03-26 17:48:19.059","caller":"global/app.go:66","msg":"日志发送失败: 订单处理结果消息发布失败 - 错误详情: Exception (504) Reason: \"channel/connection is not open\"\n"}
{"level":"error","timestamp":"2024-03-26 17:48:19.059","caller":"global/app.go:67","msg":"Exception (504) Reason: \"channel/connection is not open\""}
{"level":"error","timestamp":"2024-03-26 17:48:19.064","caller":"global/app.go:66","msg":"日志发送失败: 订单处理结果消息发布失败 - 错误详情: Exception (504) Reason: \"channel/connection is not open\"\n"}
{"level":"error","timestamp":"2024-03-26 17:48:19.064","caller":"global/app.go:67","msg":"Exception (504) Reason: \"channel/connection is not open\""}
{"level":"error","timestamp":"2024-03-26 17:48:19.068","caller":"global/app.go:66","msg":"日志发送失败: 订单处理结果消息发布失败 - 错误详情: Exception (504) Reason: \"channel/connection is not open\"\n"}
{"level":"error","timestamp":"2024-03-26 17:48:19.068","caller":"global/app.go:67","msg":"Exception (504) Reason: \"channel/connection is not open\""}
{"level":"error","timestamp":"2024-03-26 17:48:19.072","caller":"global/app.go:66","msg":"日志发送失败: 订单处理结果消息发布失败 - 错误详情: Exception (504) Reason: \"channel/connection is not open\"\n"}
{"level":"error","timestamp":"2024-03-26 17:48:19.072","caller":"global/app.go:67","msg":"Exception (504) Reason: \"channel/connection is not open\""}
{"level":"error","timestamp":"2024-03-26 17:48:19.076","caller":"global/app.go:66","msg":"日志发送失败: 订单处理结果消息发布失败 - 错误详情: Exception (504) Reason: \"channel/connection is not open\"\n"}
{"level":"error","timestamp":"2024-03-26 17:48:19.076","caller":"global/app.go:67","msg":"Exception (504) Reason: \"channel/connection is not open\""}
{"level":"error","timestamp":"2024-03-26 17:48:19.081","caller":"global/app.go:66","msg":"日志发送失败: 订单处理结果消息发布失败 - 错误详情: Exception (504) Reason: \"channel/connection is not open\"\n"}
{"level":"error","timestamp":"2024-03-26 17:48:19.081","caller":"global/app.go:67","msg":"Exception (504) Reason: \"channel/connection is not open\""}
{"level":"error","timestamp":"2024-03-26 17:48:19.085","caller":"global/app.go:66","msg":"日志发送失败: 订单处理结果消息发布失败 - 错误详情: Exception (504) Reason: \"channel/connection is not open\"\n"}
{"level":"error","timestamp":"2024-03-26 17:48:19.085","caller":"global/app.go:67","msg":"Exception (504) Reason: \"channel/connection is not open\""}
{"level":"error","timestamp":"2024-03-26 17:48:19.089","caller":"global/app.go:66","msg":"日志发送失败: 订单处理结果消息发布失败 - 错误详情: Exception (504) Reason: \"channel/connection is not open\"\n"}
{"level":"error","timestamp":"2024-03-26 17:48:19.089","caller":"global/app.go:67","msg":"Exception (504) Reason: \"channel/connection is not open\""}
{"level":"error","timestamp":"2024-03-26 17:48:19.093","caller":"global/app.go:66","msg":"日志发送失败: 订单处理结果消息发布失败 - 错误详情: Exception (504) Reason: \"channel/connection is not open\"\n"}
{"level":"error","timestamp":"2024-03-26 17:48:19.093","caller":"global/app.go:67","msg":"Exception (504) Reason: \"channel/connection is not open\""}
{"level":"error","timestamp":"2024-03-26 17:48:19.098","caller":"global/app.go:66","msg":"日志发送失败: 订单处理结果消息发布失败 - 错误详情: Exception (504) Reason: \"channel/connection is not open\"\n"}
{"level":"error","timestamp":"2024-03-26 17:48:19.098","caller":"global/app.go:67","msg":"Exception (504) Reason: \"channel/connection is not open\""}
{"level":"error","timestamp":"2024-03-26 17:48:19.102","caller":"global/app.go:66","msg":"日志发送失败: 订单处理结果消息发布失败 - 错误详情: Exception (504) Reason: \"channel/connection is not open\"\n"}
{"level":"error","timestamp":"2024-03-26 17:48:19.102","caller":"global/app.go:67","msg":"Exception (504) Reason: \"channel/connection is not open\""}
{"level":"error","timestamp":"2024-03-26 17:48:19.106","caller":"global/app.go:66","msg":"日志发送失败: 订单处理结果消息发布失败 - 错误详情: Exception (504) Reason: \"channel/connection is not open\"\n"}
{"level":"error","timestamp":"2024-03-26 17:48:19.106","caller":"global/app.go:67","msg":"Exception (504) Reason: \"channel/connection is not open\""}
{"level":"error","timestamp":"2024-03-26 17:48:19.110","caller":"global/app.go:66","msg":"日志发送失败: 订单处理结果消息发布失败 - 错误详情: Exception (504) Reason: \"channel/connection is not open\"\n"}
{"level":"error","timestamp":"2024-03-26 17:48:19.110","caller":"global/app.go:67","msg":"Exception (504) Reason: \"channel/connection is not open\""}
{"level":"error","timestamp":"2024-03-26 17:48:19.114","caller":"global/app.go:66","msg":"日志发送失败: 订单处理结果消息发布失败 - 错误详情: Exception (504) Reason: \"channel/connection is not open\"\n"}
{"level":"error","timestamp":"2024-03-26 17:48:19.114","caller":"global/app.go:67","msg":"Exception (504) Reason: \"channel/connection is not open\""}
{"level":"error","timestamp":"2024-03-26 17:48:19.118","caller":"global/app.go:66","msg":"日志发送失败: 订单处理结果消息发布失败 - 错误详情: Exception (504) Reason: \"channel/connection is not open\"\n"}
{"level":"error","timestamp":"2024-03-26 17:48:19.118","caller":"global/app.go:67","msg":"Exception (504) Reason: \"channel/connection is not open\""}
{"level":"error","timestamp":"2024-03-26 17:48:19.123","caller":"global/app.go:66","msg":"日志发送失败: 订单处理结果消息发布失败 - 错误详情: Exception (504) Reason: \"channel/connection is not open\"\n"}
{"level":"error","timestamp":"2024-03-26 17:48:19.123","caller":"global/app.go:67","msg":"Exception (504) Reason: \"channel/connection is not open\""}
{"level":"error","timestamp":"2024-03-26 17:48:19.127","caller":"global/app.go:66","msg":"日志发送失败: 订单处理结果消息发布失败 - 错误详情: Exception (504) Reason: \"channel/connection is not open\"\n"}
{"level":"error","timestamp":"2024-03-26 17:48:19.127","caller":"global/app.go:67","msg":"Exception (504) Reason: \"channel/connection is not open\""}
{"level":"error","timestamp":"2024-03-26 17:48:19.131","caller":"global/app.go:66","msg":"日志发送失败: 订单处理结果消息发布失败 - 错误详情: Exception (504) Reason: \"channel/connection is not open\"\n"}
{"level":"error","timestamp":"2024-03-26 17:48:19.131","caller":"global/app.go:67","msg":"Exception (504) Reason: \"channel/connection is not open\""}
{"level":"error","timestamp":"2024-03-26 17:48:19.135","caller":"global/app.go:66","msg":"日志发送失败: 订单处理结果消息发布失败 - 错误详情: Exception (504) Reason: \"channel/connection is not open\"\n"}
{"level":"error","timestamp":"2024-03-26 17:48:19.135","caller":"global/app.go:67","msg":"Exception (504) Reason: \"channel/connection is not open\""}
{"level":"error","timestamp":"2024-03-26 17:48:19.138","caller":"global/app.go:66","msg":"日志发送失败: 订单处理结果消息发布失败 - 错误详情: Exception (504) Reason: \"channel/connection is not open\"\n"}
{"level":"error","timestamp":"2024-03-26 17:48:19.139","caller":"global/app.go:67","msg":"Exception (504) Reason: \"channel/connection is not open\""}
{"level":"error","timestamp":"2024-03-26 17:48:19.143","caller":"global/app.go:66","msg":"日志发送失败: 订单处理结果消息发布失败 - 错误详情: Exception (504) Reason: \"channel/connection is not open\"\n"}
{"level":"error","timestamp":"2024-03-26 17:48:19.143","caller":"global/app.go:67","msg":"Exception (504) Reason: \"channel/connection is not open\""}
{"level":"error","timestamp":"2024-03-26 17:48:19.147","caller":"global/app.go:66","msg":"日志发送失败: 订单处理结果消息发布失败 - 错误详情: Exception (504) Reason: \"channel/connection is not open\"\n"}
{"level":"error","timestamp":"2024-03-26 17:48:19.147","caller":"global/app.go:67","msg":"Exception (504) Reason: \"channel/connection is not open\""}
{"level":"error","timestamp":"2024-03-26 17:48:19.151","caller":"global/app.go:66","msg":"日志发送失败: 订单处理结果消息发布失败 - 错误详情: Exception (504) Reason: \"channel/connection is not open\"\n"}
{"level":"error","timestamp":"2024-03-26 17:48:19.152","caller":"global/app.go:67","msg":"Exception (504) Reason: \"channel/connection is not open\""}
{"level":"error","timestamp":"2024-03-26 17:48:19.155","caller":"global/app.go:66","msg":"日志发送失败: 订单处理结果消息发布失败 - 错误详情: Exception (504) Reason: \"channel/connection is not open\"\n"}
{"level":"error","timestamp":"2024-03-26 17:48:19.155","caller":"global/app.go:67","msg":"Exception (504) Reason: \"channel/connection is not open\""}
{"level":"error","timestamp":"2024-03-26 17:48:19.160","caller":"global/app.go:66","msg":"日志发送失败: 订单处理结果消息发布失败 - 错误详情: Exception (504) Reason: \"channel/connection is not open\"\n"}
{"level":"error","timestamp":"2024-03-26 17:48:19.160","caller":"global/app.go:67","msg":"Exception (504) Reason: \"channel/connection is not open\""}
{"level":"error","timestamp":"2024-03-26 17:50:05.523","caller":"global/app.go:66","msg":"日志发送失败: 秒杀请求-请求入队错误 - 错误详情: Exception (504) Reason: \"channel/connection is not open\"\n"}
{"level":"error","timestamp":"2024-03-26 17:50:05.523","caller":"global/app.go:67","msg":"Exception (504) Reason: \"channel/connection is not open\""}
